(() => {
  const state = { screen: 'home', name: 'Asha Sharma', visit: 'first', language: 'English', abha: '', answers: {}, question: 0, scanned: false, priority: false, online: true, completed: 24 };
  const questions = [
    ['complaint', 'What brings you in today?', 'Choose the closest answer, or tell us in your own words.', ['Pain or discomfort', 'Fever, cough or cold', 'Digestive concern', 'Follow-up or medicine review']],
    ['start', 'When did this start?', 'This helps the clinician understand the concern.', ['Today', 'A few days ago', 'More than a week ago', 'It comes and goes']],
    ['severity', 'How severe is it right now?', 'Choose the closest answer. Tell staff immediately if it feels urgent.', ['Mild - manageable', 'Moderate - affects routine', 'Severe - hard to manage', 'Emergency symptoms']],
    ['history', 'Do you have allergies or regular medicines?', 'Include prescribed, AYUSH, and herbal medicines.', ['No known allergies or regular medicines', 'Medicine allergy', 'Prescription medicine', 'AYUSH or herbal medicine']],
    ['ayush', 'Would you like to add AYUSH wellness details?', 'This is optional and can be discussed with the clinician.', ['Add AYUSH profile', 'Skip for this visit', 'I need help answering']]
  ];
  const $ = selector => document.querySelector(selector);
  const $$ = selector => [...document.querySelectorAll(selector)];
  function toast(message) { const el = document.createElement('div'); el.className = 'toast'; el.textContent = message; $('#toast-area').replaceChildren(el); setTimeout(() => el.remove(), 3000); }
  function show(screen) { state.screen = screen; $$('.screen').forEach(el => el.classList.toggle('active', el.id === `${screen}-screen`)); window.scrollTo({top: 0, behavior: 'smooth'}); if (screen === 'intake') renderQuestion(); if (screen === 'review') renderSummary(); }
  $$('[data-screen]').forEach(button => button.addEventListener('click', () => show(button.dataset.screen)));
  $$('.option').forEach(button => button.addEventListener('click', () => { $$('.option').forEach(x => x.classList.remove('selected')); button.classList.add('selected'); state.visit = button.dataset.visit; }));
  function beginAfterAuthentication(abha) { state.language = $('#language').value; state.abha = abha; state.name = 'Asha Sharma'; show('identify'); }
  $('#verify-login').addEventListener('click', () => { const abha = $('#login-abha').value.trim(); if (!abha) return toast('Enter an ABHA number or use the demo profile.'); beginAfterAuthentication(abha); toast('ABHA verified for this prototype.'); });
  $('#bypass-login').addEventListener('click', () => { beginAfterAuthentication('98-7654-3210-9876'); toast('Demo ABHA profile selected.'); });
  $('#continue-identify').addEventListener('click', () => show('intake'));
  function renderQuestion() { const [key, title, help, options] = questions[state.question]; $('#question-title').textContent = title; $('#question-help').textContent = help; $('#question-count').textContent = `Question ${state.question + 1} of ${questions.length}`; $('#progress-bar').style.width = `${((state.question + 1) / questions.length) * 100}%`; $('#other-answer').value = state.answers[`${key}-other`] || ''; const answers = $('#answers'); answers.innerHTML = ''; options.forEach(option => { const b = document.createElement('button'); b.type = 'button'; b.className = `answer ${option === 'Emergency symptoms' ? 'urgent' : ''} ${state.answers[key] === option ? 'selected' : ''}`; b.textContent = option; b.addEventListener('click', () => { state.answers[key] = option; $$('.answer').forEach(x => x.classList.toggle('selected', x.textContent === option)); if (option === 'Emergency symptoms') { state.priority = true; $('#triage-modal').classList.remove('hidden'); } }); answers.append(b); }); $('#previous-question').style.visibility = state.question ? 'visible' : 'hidden'; $('#next-question').innerHTML = state.question === questions.length - 1 ? 'Continue to records <span>→</span>' : 'Continue <span>→</span>'; }
  $('#next-question').addEventListener('click', () => { const key = questions[state.question][0]; const typed = $('#other-answer').value.trim(); if (typed) state.answers[`${key}-other`] = typed; if (!state.answers[key] && !typed) { toast('Choose an answer or add a short detail to continue.'); return; } if (state.question === questions.length - 1) show('scan'); else { state.question += 1; renderQuestion(); } });
  $('#previous-question').addEventListener('click', () => { if (state.question) { state.question -= 1; renderQuestion(); } });
  function speak(text) { if (!('speechSynthesis' in window)) return toast('Audio guidance is ready on kiosk devices.'); speechSynthesis.cancel(); const utterance = new SpeechSynthesisUtterance(text); utterance.lang = state.language === 'हिंदी (Hindi)' ? 'hi-IN' : 'en-IN'; speechSynthesis.speak(utterance); }
  $('#welcome-audio').addEventListener('click', () => speak('Welcome to MediKiosk. Choose your language, then sign in with ABHA or continue with the demo profile.'));
  $('#speak-question').addEventListener('click', () => speak(`${$('#question-title').textContent}. ${$('#question-help').textContent}`));
  $('#consent-audio').addEventListener('click', () => speak('Please choose what you agree to share for today’s clinical summary. You can change these choices before continuing.'));
  $('#microphone').addEventListener('click', () => { $('#microphone').classList.toggle('listening'); const recording = $('#microphone').classList.contains('listening'); $('#mic-label').textContent = recording ? 'Listening… tap again when finished' : 'Voice answer captured'; if (!recording && !state.answers[questions[state.question][0]]) state.answers[questions[state.question][0]] = 'Voice response captured'; });
  $('#safety-note').addEventListener('click', () => { state.priority = true; $('#triage-modal').classList.remove('hidden'); });
  $('#close-triage').addEventListener('click', () => { $('#triage-modal').classList.add('hidden'); toast('Priority marker added for staff review.'); });
  function scan(fileName) { state.scanned = true; $('#scan-box').classList.add('hidden'); $('#scan-result').classList.remove('hidden'); $('#scan-progress').textContent = `Reading ${fileName}…`; setTimeout(() => { $('#scan-progress').textContent = 'Document read'; $('#extracted').classList.remove('hidden'); $('#interaction').classList.remove('hidden'); $('#continue-scan').disabled = false; $('#continue-scan').classList.remove('disabled'); }, 900); }
  $('#upload').addEventListener('change', e => { if (e.target.files[0]) scan(e.target.files[0].name); });
  $('#sample-scan').addEventListener('click', () => scan('sample prescription'));
  $('#skip-scan').addEventListener('click', () => { $('#consent-language').textContent = state.language; show('consent'); });
  $('#continue-scan').addEventListener('click', () => { $('#consent-language').textContent = state.language; show('consent'); });
  $('#make-draft').addEventListener('click', () => { if (!$('#summary-consent').checked) return toast('Consent for today’s clinical summary is needed to continue.'); show('review'); });
  function value(key, fallback) { return state.answers[`${key}-other`] || state.answers[key] || fallback; }
  function renderSummary() { $('#summary-name').textContent = state.name; $('#summary-meta').textContent = `${state.abha || 'ABHA not verified'} · ${state.language}`; const items = [ ['Chief complaint', value('complaint', 'Not recorded'), 'high', 'Confirmed'], ['Present concern', `${value('start', 'Onset not recorded')}; ${value('severity', 'severity not recorded')}.`, 'medium', 'Check'], ['Medicines and allergies', `${value('history', 'No details recorded')}${state.scanned ? '. Reported medicines transcribed from the scanned record: Ashwagandha and Levothyroxine.' : ''}`, state.scanned ? 'medium' : 'low', state.scanned ? 'Check' : 'Inferred'], ['AYUSH context', value('ayush', 'Not added for this visit'), 'low', 'Inferred'], ['Safety and document review', `${state.priority ? 'Priority marker present. ' : ''}${state.scanned ? 'Two reported medicines were detected together; clinician review is required. No recommendation is generated.' : 'No document-based review is available.'}`, state.priority ? 'high' : 'medium', state.priority ? 'Confirmed' : 'Check'] ]; $('#summary-content').innerHTML = items.map(([title, text, tag, label]) => `<section class="summary-section"><h3>${title}<span class="tag ${tag}">${label}</span></h3><p>${text}</p></section>`).join(''); }
  $('#return-intake').addEventListener('click', () => { show('intake'); toast('Returned to the patient questions.'); });
  $('#reject-draft').addEventListener('click', () => toast('Draft rejected. It has not been routed.'));
  $('#route-summary').addEventListener('click', () => { $('#fhir-text').textContent = `FHIR handoff simulated for ${state.name}'s selected health profile.`; $('#route-modal').classList.remove('hidden'); });
  $('#clear-session').addEventListener('click', () => { $('#route-modal').classList.add('hidden'); state.completed += 1; state.answers = {}; state.question = 0; state.scanned = false; state.priority = false; $('#completed-count').textContent = state.completed; $('#review-count').textContent = Math.max(0, Number($('#review-count').textContent) - 1); $('#scan-box').classList.remove('hidden'); $('#scan-result').classList.add('hidden'); $('#continue-scan').disabled = true; $('#continue-scan').classList.add('disabled'); $('#upload').value = ''; toast('Kiosk session cleared.'); show('home'); });
  $('#connection').addEventListener('click', () => { state.online = !state.online; $('#connection').classList.toggle('offline', !state.online); $('#connection-label').textContent = state.online ? 'Connected' : 'Offline queue'; $('#offline-count').textContent = state.online ? '0' : '1'; toast(state.online ? 'Connection restored.' : 'Offline capture mode enabled.'); });
  $('#accessibility').addEventListener('click', () => { document.body.classList.toggle('large-text'); toast('Text size updated.'); });
})();
